### ISSUE TITLE
How can I set timeout for https?

### ISSUE THREAD

**Issue by leetking** [brunoos/luasec#112]
I want to set timeout for `ssl.https`.
I know add timeout for `socket.http` by custem `create` function which creates a tcp connection and settimeout. I want to achieve this aim through same way, but it doesn't work, and thumb through file [https.lua](https://github.com/brunoos/luasec/blob/master/src/https.lua#L83). According to my understand, there is no method to add tiemout.

**Comment by brunoos** [comment]
https relies on http from LuaSocket, if you set "http.TIMEOUT" it will affect https.

https://github.com/diegonehab/luasocket/blob/master/src/http.lua#L119

**Comment by leetking** [comment]
Thanks a lot. :+1: 
It works for the timeout of https, but I just find my demo is blocked at the handshake of ssl due to the handshake failure about the certification is invalid. I am sure that the reason of the handshake failure is that I need identify first to use the net.
So how can I dominate the process of ssl handshake of https, or close connection of request immediately at first handshake failure?

**Comment by brunoos** [comment]
wait... I think I was wrong....

When LuaSocket's http calls settimeout(), it will affect the socket object only. The SSL object will be created after, when connect() is called. Since socket and SSL are different objects, the information about timeout is not shared and the SSL handshake will use the default timeout, that is blocking forever.

**Comment by leetking** [comment]
Thanks very much. Would you mind to improve thant we can control the timeout of SSL?

**Comment by brunoos** [comment]
Timeout added in 953a363a59d4331148bb69ea7cd254a52784557e

**Comment by decadence** [comment]
Does this support fractional seconds?

Is this timeout for all operation or for individual connect, read, write?

**Comment by Tieske** [comment]
afaik LuaSocket (and LusSec) only have 1 timeout setting, used for all operations.

**Comment by yois615** [comment]
I have tried every possible way to set a timeout for https.request and nothing works.

Something I'm not understanding:


> https relies on http from LuaSocket, if you set "http.TIMEOUT" it will affect https.
> 
> https://github.com/diegonehab/luasocket/blob/master/src/http.lua#L119

How does that work?  This is legal:

```
foo = require "socket.http"
bar = require "ssl.https"
```
so how would setting
`foo.TIMEOUT = 5`


impact on `bar`? `bar` is unrelated to `foo`!  I set it anyway and it had no effect.

I also set 
`bar.TIMEOUT = 5`

and it also had no effect, requests will continue indefinitely causing deadlocks.  I probably missing something because as is this library is unusable to me.
