### ISSUE TITLE
luasec fails to build on windows x64 with mingw for lua5.3.4

### ISSUE THREAD

**Issue by Mehgugs** [brunoos/luasec#113]
Using openssl compiled with mingw64, luarocks reports it building successfully however I get this error when loading the module into lua5.3.4:
```> ssl = require"ssl"
error loading module 'ssl.core' from file 'C:\program files\lua\5.3\lib\lua\5.3\ssl.dll':
        The specified module could not be found.
```

**Comment by brunoos** [comment]
Were your LUA_PATH and LUA_CPATH variables correct?

**Comment by Mehgugs** [comment]
My LUA_PATH and LUA_CPATH are correct, like i said luarocks reports that it is installed successfully, this only happens upon trying to load the module. I have successfully compiled libz and installed luazlib using my current setup, which is what leads me to think it is possibly an issue with the way luasec is built on windows and not an issue with my lua setup itself.

**Comment by Tieske** [comment]
@Mehgugs have you tried putting the OpenSSL dll's next to the Lua executable?

The `LUA_PATH` and `LUA_CPATH` variables are of no use here. Those are the ones that Lua uses to load a module. In this case it uses `LUA_CPATH` to load `C:\program files\lua\5.3\lib\lua\5.3\ssl.dll` and that clearly works. 
The problem is that that binary Lua module tries to load another dll. This loading of the dll is outside the scope of Lua, and uses the regular Windows rules for finding the dll.
Iirc Windows will use either the current working directory or the directory where the application executable is located (in this case `lua.exe`) to look for the dll's.

Hence my suggestion: put the OpenSSL dll's next to the Lua executable.

**Comment by pkulchenko** [comment]
@Mehgugs, I agree with @Tieske; this is the best recommendation, but if you need to have ddls in a different folder, you may apply something like that following that I have in my version of ssl.lua:

```
if package.config:sub(1,1) == "\\" then -- Windows only
  -- this hack is needed because OpenSSL libraries may be available elsewhere
  -- and loading them using the full path ensures that the right versions are un/loaded.
  -- don't need to request any function as only need to load libraries. -- PK
  local bindir = debug.getinfo(1,'S').source:gsub("[^/\\]+$",""):gsub("^@","").."../bin/"
  package.loadlib(bindir.."libeay32.dll", "")
  package.loadlib(bindir.."ssleay32.dll", "")
end
```

**Comment by Mehgugs** [comment]
okay, this would explain why it had no issues while compiling I guess. I had a look in my installation and cannot locate those particular dll files, I have "installed opensll" yet it produces `libssl-1_1-x64.dll` and `libcrypto-1_1-x64.dll` and not files including the `libeay` or `ssleay`.
I'm not sure what I'm missing here (it's probably the wrong version *face palm*) but it's probably beyond the scope of luasec so I'm going to close this. Thanks for helping anyway and apologies for my ineptitude xD

**Comment by Tieske** [comment]
I never tried the x64 versions, ever only worked with 32bit ones, maybe the names are different there?

**Comment by daurnimator** [comment]
The OpenSSL 1.1.0 release renamed the DLLs.
