### ISSUE TITLE
Access with https but responded with 301

### ISSUE THREAD

**Issue by kometchtech** [brunoos/luasec#117]
As I was investigating to download files using lua, I came to luasec.

I created the following test code and checked the status code, but when I visit the following website, the status code will be answered with 301.

```
# lua test.lua
HTTP/1.1 301 Moved Permanently
```
```
require("socket")
local https = require("ssl.https")
local body, code, headers, status = https.request{
        url = "https://www.internic.net/domain/named.root",
}
print(status)
```
https://stackoverflow.com/questions/8286677/https-request-in-lua
http://notebook.kulchenko.com/programming/https-ssl-calls-with-lua-and-luasec

Although some people created similar issues in the past, do they have similar problems?

[Problem with https.request #51 ](https://github.com/brunoos/luasec/issues/51)

**env:**

- Linux 4.4.126 aarch64 Linux
- lua5.1-5.1.5-r7 aarch64 {lua5.1} (MIT) [installed]
- lua5.1-libs-5.1.5-r7 aarch64 {lua5.1} (MIT) [installed]
- lua5.1-socket-3.0_rc1_git20160306-r2 aarch64 {lua-socket} (MIT) [installed]
- lua5.1-sec-0.6-r4 aarch64 {lua-sec} (MIT) [installed]

Best regards.

**Comment by ewestbrook** [comment]
The server at `www.internic.net:443` seems confused by `Host:` request headers that specify the port number unnecessarily.

`Host:` Header | Status | Result
-----|-----|-----
 `Host: www.internic.net:443` | 301 | Redirect to `Location: https://www.internic.net/domain/named.root`
 `Host: www.internic.net`| 200 | The requested document

Hilariously, the above holds regardless of which transport is used, HTTP (80) or HTTPS (443).

This is unfortunate, of course, because [luasocket](https://github.com/diegonehab/luasocket)'s `socket.http` module adds `:443` without exception when called this way (i.e. via `require'ssl.https'.request()`).

That's supposed to be okay, per [RFC2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23).  Yet for this site it's clearly not!

In any case, [this patch](https://github.com/ewestbrook/luasocket/commit/dfbf686c2e396c79619ca4bd6388e87cde2ee09a) seems to get it done.

(That code is actually part of other `luasocket` work-in-progress that I hope to PR soon; I've just snipped it here for quick use in case it helps.)

**Comment by kometchtech** [comment]
Thank you for the information.
I also understood the status of waiting for the corresponding patch merge.
I will wait to be formally merged.

**Comment by vcunat** [comment]
_Notified ICANN who runs those servers._

**Comment by paulehoffman** [comment]
Unofficial note from an ICANN person: you should now get a full response even if you have a bad Host: header.

**Comment by ewestbrook** [comment]
Confirmed.  Thanks!

Without the erroneous one, there's now no HTTP to HTTPS redirect at all.  I hope they intended that.

Also, a nit:

> even if you have a bad Host: header

The Host: header was never "bad", according to [RFC2616](https://www.w3.org/Protocols/rfc2616).  Sure, the redundant port number was unnecessary, but certainly not illegal.

**Comment by brunoos** [comment]
Is there something to do in this issue?

**Comment by ewestbrook** [comment]
Not here, that's for sure. The site in question fixed its responses regardless, and my patch above is for luasocket anyway. For safety's sake, I should particularly now work it up the chain over there, which I will. All set here. Thanks for following up!
