### ISSUE TITLE
Problem with https.request

### ISSUE THREAD

**Issue by GorgonzolaPasta** [brunoos/luasec#51]
Hi,
I am having trouble with the following piece of code:
``` lua
local https = require("ssl.https")
https.request("https://de.wiktionary.org/wiki/%26")
```

```
luajit test.lua
PANIC: unprotected error in call to Lua API (?)
```
Some info:
```
luasec
   0.5-2 (installed) - /usr/local/lib/luarocks/rocks-5.1
```

```
luajit -v
LuaJIT 2.0.4 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/
```
```
openssl version
OpenSSL 1.0.1l-freebsd 15 Jan 2015
```
```
uname -a
FreeBSD x230 10.1-RELEASE-p6 FreeBSD 10.1-RELEASE-p6 #0: Tue Feb 24 19:00:21 UTC 2015     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

**Comment by brunoos** [comment]
Nothing here... is there some more info?

$ luajit test.lua 
nil	closed	nil	nil

----
$ luarocks help
LuaRocks 2.2.2, a module deployment system for Lua

$ luarocks list     
luasec
   0.5-2 (installed) - /home/brunoos/local/rocks-5.1/lib/luarocks/rocks
luasocket
   3.0rc1-2 (installed) - /home/brunoos/local/rocks-5.1/lib/luarocks/rocks

$ luajit -v 
LuaJIT 2.0.4 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/

$ openssl version
OpenSSL 1.0.1l-freebsd 15 Jan 2015

$ uname -a
FreeBSD freebsd10 10.1-RELEASE-p10 FreeBSD 10.1-RELEASE-p10 #0: Wed May 13 06:54:13 UTC 2015     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

**Comment by GorgonzolaPasta** [comment]
What could I try? What info can I give you?

**Comment by brunoos** [comment]
Did you compile "luajit" yourself?

**Comment by GorgonzolaPasta** [comment]
I installed it with pkg.

**Comment by GorgonzolaPasta** [comment]
I get the same problem when installing lua from ports.

**Comment by brunoos** [comment]
The problem is the automatic redirection from socket.http. It tries to connect on port 80, but it is https.

$ lua test.lua
301	HTTP/1.1 301 Moved Permanently
redirect	https://de.wiktionary.org/wiki/%26
path	/wiki/%26
create	function: 0x7fb94b430cd0
authority	de.wiktionary.org
host	de.wiktionary.org
port	80
nredirects	1
scheme	https
url	https://de.wiktionary.org/wiki/%26
uri	/wiki/&
headers	table: 0x7fb94b42e3d0

We know the issue, but we need some commits on luasocket to address it.

However, Firefox does not receive a 301 code from the site. Using firebug I noticed that Firefox send "/wiki/%26" as request, but luasocket send "/wiki/&", i.e., it unescape the URL.

Typing "https://de.wiktionary.org/wiki/&" on Firefox, I received a 301 also.

If I force socket.http to request "/wiki/%26" it works fine.

So, even if you turn off auto-redirect, you still have problem in the request.

(?)

**Comment by GorgonzolaPasta** [comment]
```If I force socket.http to request "/wiki/%26" it works fine.```
How do I do that?

And is there an issue in the luasocket reposetory already?

**Comment by brunoos** [comment]
In this case, edit socket/url.lua and remove "&" from the list of unescaped.

```
-- these are allowed withing a path segment, along with alphanum
-- other characters must be escaped
local segment_set = make_set {
    "-", "_", ".", "!", "~", "*", "'", "(",
--    ")", ":", "@", "&", "=", "+", "$", ",",
    ")", ":", "@", "=", "+", "$", ",",
}
```

Do not ask me what it could happen with other URLs.

Tieske already submit a PR.
