### ISSUE TITLE
SSLv3 removed from Debian

### ISSUE THREAD

**Issue by gares** [brunoos/luasec#58]
As per version 1.0.2d-2, the SSLv3_* API has been disabled in Debian.
  http://metadata.ftp-master.debian.org/changelogs//main/o/openssl/openssl_1.0.2d-3_changelog
Can you help me choosing the right replacement?

**Comment by gares** [comment]
See also: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=804607

**Comment by brunoos** [comment]
PR #55 added guards to SSLv3_method(). Is it enough?

**Comment by gares** [comment]
It builds fine if I cherry-pick that commit on top of 0.5, but then the test I run as part of the package build fails.  In particular samples/oneshot/server.lua choses as protocol "sslv3".  What should I use instead?

**Comment by gares** [comment]
The openssl maintainer suggested to switch to "sslv23" in all the examples.  I guess you may want to apply that to all examples.

**Comment by brunoos** [comment]
I updated to 'tlsv1'.

**Comment by gares** [comment]
Quoting Kurt: "A few use tlsv1 which isn't much better."

I'm no expert, I'll ask him why on the Debian bugreport

**Comment by daurnimator** [comment]
`SSLv23_method` is always the 'safe' default (which might be TLS 1.2). Any reason not to use that?

**Comment by brunoos** [comment]
no problem in use 'sslv23'. But...

OpenSSL renamed it to TLS_method(), because the earlier name has no meaning anymore.
Forks like LibreSSL still have SSLv23_method.

As suggestion from @gleydsonsoares, we can add 'all' (or 'any'?) as an alias to 'sslv23' (deprecating it), and avoid to expose this details to user.

'tlsv1' was an intermediate and conservative option until the change.

**Comment by mwild1** [comment]
I like that :)

**Comment by kroeckx** [comment]
Just to clarify, if the other side talks TLS 1.2, you really should use it.  Just like there is an RFC to make SSLv3 die, there are people who already want to disable TLS 1.0.
